version: "3"

services:
  app:
    container_name: app
    restart: on-failure
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_ALIAS=${MONGODB_ALIAS}
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - FIREBASE_CONFIG=${FIREBASE_CONFIG}  # path to .json file
      - APP_NAME=${APP_NAME}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-router.rule=Host(`app.localhost`)"
      - "traefik.http.routers.app-router.entrypoints=websecure"
      - "traefik.http.routers.app-router.tls.certresolver=myresolver"
    volumes:
      - "app:/data/app"
    networks:
      - mongo_default
      - redis_default
      - backend

volumes:
  app:

networks:
  mongo_default:
    external: true
  redis_default:
    external: true
  backend:
    external: true